apiVersion: v1
kind: Service
metadata:
  name: clickhouse-svc
  namespace: clickhouse
spec:
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: 8123
    name: http
  - port: 9000
    targetPort: 9000
    name: tcp
  - port: 9009
    targetPort: 9009
    name: interserver
  selector:
    app: clickhouse
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-external
  namespace: clickhouse
spec:
  type: LoadBalancer
  ports:
  - port: 8123
    targetPort: 8123
    name: http
  - port: 9000
    targetPort: 9000
    name: tcp
  selector:
    app: clickhouse